["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
strategy_manager = [
    "src/strategy_manager.cairo",
]
Cooperator = [
    "src/Cooperator.cairo",
]
Defector = [
    "src/Defector.cairo",
]
Tit4Tat = [
    "src/Tit4Tat.cairo",
]