["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
strategy_manager = [
    "src/strategy_manager.cairo",
]
player_strategy_one = [
    "src/player_strategy_one.cairo",
]
player_strategy_two = [
    "src/player_strategy_two.cairo",
]
player_strategy_tit_tat = [
    "src/player_strategy_tit_tat.cairo",
]